### ISSUE TITLE
Cover all basic resources for AWS

### ISSUE THREAD

**Issue by ttarczynski** [ContainerSolutions/terraform-examples#48]
- [x] #108
- [x] #110
- [x] #111
- [x] #113
- [x] #114
- [x] #116
- [x] #118
- [x] #117
- [ ] #119
- [ ] #120
- [ ] #109

**Comment by ttarczynski** [comment]
Partially done:
* Kubernetes:
** [aws/aws_eks/fargate/spot_and_fargate](https://github.com/ContainerSolutions/terraform-examples/tree/main/aws/aws_eks/fargate/spot_and_fargate)
** need to add a **simple** example
* IAM
** [aws/aws_iam/groups](https://github.com/ContainerSolutions/terraform-examples/tree/main/aws/aws_iam/groups)
** need to add a **simple** example

**Comment by rodrigorras** [comment]
Started working on this branch https://github.com/ContainerSolutions/terraform-examples/tree/aws-persistent-storage-rodrigo  for Storage persistent volume. I guess I will create two folders aws_ebs_persistent_storage. Ok with that?
