### ISSUE TITLE
Add contributor's guide

### ISSUE THREAD

**Issue by ttarczynski** [ContainerSolutions/terraform-examples#59]
We need a guide that will help new contributors when working on their first pull request.
Such guide should:
- describe the contributing process (e.g. issues, milestones, submitting a pull request, etc.)
- list all conventions and requirements for the examples
  - see: [README.md > conventions](https://github.com/ContainerSolutions/terraform-examples/blob/main/README.md#conventions)
- explain the principles of this project 
  - see: [README.md > principles](https://github.com/ContainerSolutions/terraform-examples/blob/main/README.md#principles)
- explain how the CI checks work and explain how to run them locally
  - see: [README.md > github-actions-workflow](https://github.com/ContainerSolutions/terraform-examples/blob/main/README.md#github-actions-workflow)

Some information are already in [README.md](https://github.com/ContainerSolutions/terraform-examples/blob/main/README.md), but we need to make it easier for first-time contributors.

**Comment by teszes** [comment]
Should this be separated into a "CONTRIBUTING.md"?

**Comment by ttarczynski** [comment]
Yes, I think `CONTRIBUTING.md` would be the way to go (and link it in `README.md`).
