### ISSUE TITLE
CI test 'ProvidersAzure' stopped working

### ISSUE THREAD

**Issue by ttarczynski** [ContainerSolutions/terraform-examples#69]
After the recent change #56 our CI test `ProvidersAzure` stopped working. 
See:
- Test definition: [.github/workflows/main.yml#L128-L150](https://github.com/ContainerSolutions/terraform-examples/blob/main/.github/workflows/main.yml#L128-L150)
- Last test run on `integration` branch: https://github.com/ContainerSolutions/terraform-examples/runs/3022667473?check_suite_focus=true

Results from `ProvidersAzure` test:
```
Run /home/runner/work/terraform-examples/terraform-examples/bin/run_azurerm_examples.sh
find: ‘azurerm’: No such file or directory
```

The problem is caused by renaming `azurerm` to `azure` without the needed changes in CI and `bin/*.sh` scripts:
```
# egrep -r azurerm bin
bin/run_azurerm_examples.sh:source bin/get_azurerm_folders.sh
bin/apply.sh:SUPPORTED_PROVIDERS="aws|azurerm|digitalocean|google|kubernetes|linode"
bin/get_azurerm_folders.sh:AZURERM_FOLDERS="$(find azurerm | grep tf$ | xargs -n1 dirname | sed 's/^.\///')"
bin/destroy.sh:SUPPORTED_PROVIDERS="aws|azurerm|digitalocean|google|kubernetes|linode"
```
```
# egrep -r azurerm .github/workflows
.github/workflows/main.yml:        run: ${{github.workspace}}/bin/run_azurerm_examples.sh
```

**Comment by ttarczynski** [comment]
You can test it locally by running:
```
./bin/run_azurerm_examples.sh
```

**Comment by teszes** [comment]
This should be fixed on the integration branch, right?

**Comment by teszes** [comment]
What if we went back to the 1 provider - 1 folder scheme we had?

**Comment by teszes** [comment]
Submitted PR #70 to close this.

**Comment by ttarczynski** [comment]
#70 merged, tests work OK.
Closing this.
