### ISSUE TITLE
INDEX.md improvements

### ISSUE THREAD

**Issue by teszes** [ContainerSolutions/terraform-examples#81]
Right now, `INDEX.md` causes a lot of work as it needs to be touched by every PR that adds something, and it creates a lot of merge conflicts. It also is something between a glossary and a table of contents, not really conforming to either idea.

Goals we want to achieve:
* have an automated solution to generate `INDEX.md`
* avoid making any changes to `INDEX.md` when contributing new examples

In more detail:
* It could be in a form of a script
* That script can be automatically executed after every new commit to the `main` branch (GitHub Actions CI job)

**Comment by teszes** [comment]
BTW this issue originated from our meeting last week I think

**Comment by ttarczynski** [comment]
We've just discussed this topic with @melihc1 during our mob session. We've updated the issue description to reflect our current ideas.

Also, as the first prototype, we've tried the simplest possible bash commands:
```
find * -name main.tf | sort | xargs head -n1
```

It requires iterating a bit more, to add things like:
* md formatting 
* split the list into separate sections per provider / functionality (top level folders)
* exception handling (check for different possible errors)

**Comment by ttarczynski** [comment]
* There is an INDEX format proposed by the team:

## AWS Examples
| Resource                               | Feature  | Summary | 
| -------------                          |:-------------:|:-------------:|
| [aws_docdb_cluster](aws/aws_docdb_cluster)                   | [simple](aws/aws_docdb_cluster/simple) | |
| [aws_db_instance](aws/aws_db_instance)                     | [simple](aws/aws_db_instance/simple) | summary... |
| [aws_db_instance](aws/aws_db_instance)                     | [postgres](aws/aws_db_instance/postgres) | summary... |
| [aws_db_instance](aws/aws_db_instance)                     | [restore_db_from_snapshot](aws/aws_db_instance/restore_db_from_snapshot) | summary... |
| [aws_db_instance](aws/aws_db_instance)                     | [db_snapshot](aws/aws_db_instance/db_snapshot) | summary... |

**Comment by melihc1** [comment]
Continuing from previous discussions we made some progress during mob session yesterday. Currently we have work in progress in `index-creation` branch
